### ISSUE TITLE
Missing support for fish

### ISSUE THREAD

**Issue by mcepl** [openSUSE/cnf#10]
There is [`fish_command_not_found`](https://fishshell.com/docs/current/cmds/fish_command_not_found.html) handler, which can be reprogrammed in `/usr/share/fish/vendor_functions.d` to do The Right Thing™ (whatever it is).

**Comment by vyskocilm** [comment]
Tried in a freshly installed Tumbleweed and it works right after `zypper in cnf fish`

```sh
michal@tumbleweed:~> fish
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
michal@tumbleweed ~> cmake

The program 'cmake' can be found in following packages:
  * cmake-full [ path: /usr/bin/cmake, repository: repo-oss ]
  * cmake-mini [ path: /usr/bin/cmake, repository: repo-oss ]

Try installing with:
    sudo zypper install <selected_package>
```

There's an integration test verifying the `fish` support, see https://github.com/openSUSE/cnf/blob/main/test/test.bats#L66C34-L66C94 - the `/usr/share/fish/functions/fish_command_not_found.fish` should be sourced automatically and it calls `/usr/bin/command-not-found` on SUSE systems, which is provided by `cnf.rpm`.

```sh
michal@tumbleweed ~> grep -A 3 suse /usr/share/fish/functions/fish_command_not_found.fish
else if contains -- suse $os || contains -- sles $os && type -q command-not-found
    function fish_command_not_found
        command-not-found $argv[1]
    en
michal@tumbleweed ~> rpm -qf /usr/bin/command-not-found
cnf-0.6.0~0-3.2.x86_64
```

**Comment by mcepl** [comment]
You are right, I had to have something screwed up. SOrry.
