### ISSUE TITLE
Does not operate in PowerShell.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [openSUSE/cnf#8]
<blockQuote>

```.log
PowerShell 7.4.0-preview.3

   A new PowerShell stable release is available: v7.4.0 
   Upgrade now, or check out the release page at:       
     https://aka.ms/PowerShell-Release?tag=v7.4.0       

PS /home/RokeJulianLockhart> lshw
lshw: The term 'lshw' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS /home/RokeJulianLockhart> bash -c 'lshw'
/usr/bin/bash: line 1: lshw: command not found
NativeCommandExitException: Program "bash" ended with non-zero exit code: 127.
PS /home/RokeJulianLockhart> bash
RokeJulianLockhart@s1e8h4:~> lshw
Absolute path to 'lshw' is '/usr/sbin/lshw', so running it may require superuser privileges (eg. root).
RokeJulianLockhart@s1e8h4:~>
```

</blockQuote>

**Comment by RokeJulianLockhart** [comment]
> https://github.com/openSUSE/cnf/issues/8#issuecomment-1850932488

@vyskocilm, I'm not able to provide any development assistance. I can try to test fixes and workarounds, but I'm a systems administrator more than a software developer. Is https://gist.github.com/Jaykul/b8ed295d32ec2500b7becfed38308521#about-commandnotfoundaction of any use?

**Comment by vyskocilm** [comment]
I see. Lets hope that someone skilled in PowerShell will contribute a proper integration.

**Comment by mklement0** [comment]
Here's an example `command_not_found.ps1` file that somewhat emulates what `command_not_found.bash` does:

```powershell
$env:TEXTDOMAINDIR = '/usr/share/locale'
$env:TEXTDOMAIN = 'cnf'

$ExecutionContext.InvokeCommand.CommandNotFoundAction = {

  param($commandAsSubmitted, $commandLookupEventArgs)

  # Ignore the following invocations:
  #  * via a 'get-*' prefix stemming from PowerShell's default-verb logic,
  #  * via a repeated lookup in the _current_ dir. (./…) - PowerShell itself will provide feedback on that.
  #  * calls from scripts.
  if ($commandAsSubmitted -like 'Get-*' -or $commandAsSubmitted -like '.[/\]*' -or (Get-PSCallStack)[1].ScriptName) { return }

  # Determine the executable path.
  $cnf_bin = $env:COMMAND_NOT_FOUND_BIN ?? '/usr/bin/cnf'

  # Invoke and output the results directly to the terminal (host).
  & $cnf_bin $commandAsSubmitted *>&1 | Out-Host

  # Note: 
  #  * PowerShell's not-found error is seemingly invariably printed afterwards;
  #    the following does NOT prevent that:
  #       $commandLookupEventArgs.StopSearch = $true
  #  * Supposedly, returning a [System.Management.Automation.CommandInfo] instance
  #    - such as output by Get-Command - can provide the command to execute, but that 
  #    doesn't seem to work.

}
```

* This script can be invoked directly (doesn't need sourcing); e.g.. `./command_not_found.ps1`

* A call to this script (or the code it contains) is best placed in the user's [`$PROFILE`](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Profiles) file.

* As in the Bash case, the mechanism supports only _one_ custom command-not-found handler.
  * However, a plug-in system is being worked on that supports multiple third-party handlers, called _feedback providers_ - see [this blog post](https://devblogs.microsoft.com/powershell/what-are-feedback-providers/).
  * Someone could write a custom feedback provider that incorporates `cnf`, similar to the one in the [`command-not-found` provider](https://github.com/PowerShell/command-not-found); the latter currently relies solely on the presence of `/usr/lib/command-not-found`, as preinstalled on Ubuntu distros.

**Comment by vyskocilm** [comment]
Amazing work @mklement0 - would you mind sending a PR updating the README, please?

**Comment by mklement0** [comment]
Thanks, @vyskocilm. 

It isn't clear to me how to best integrate the above into the README, so I suggest you do it yourself - feel free to use whatever parts you need. 

To create a section analogous to the existing "Integrate with bash" one (which has a typo, incidentally: `command_not_found_bash` -> `command_not_found.bash`), you'd need to also add a `command_not_found.ps1` file.
